---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-fluentd-config
  namespace: {{ .Values.global.namespace }}
data:
  fluentd.conf: |
    <source>
      @type tail
      path /usr/share/elasticsearch/logs/*.log
      pos_file /tmp/log.pos
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<msg>.*)$/
        #13 Nov 2020 10:53:45.069,
        #time_format %d %m %Y %H:%M:%S.mili
      </parse>
      tag graylog2
    </source>
